---

- name: auth packages
  apt: 
    name: "{{ item }}"
    update_cache: true
  with_items: authconfig_packages

#- name: nsswitch conf
#  template:
#    src: nsswitch.conf.j2
#    dest: /etc/nsswitch.conf

# PAM module to auto-create home directories
- name: mkhomedir
  template:
    dest: '/usr/share/pam-configs/mkhomedir'
    src: 'mkhomedir.j2'
    owner: 'root'
    group: 'root'
    mode: 0644
  notify: pam-auth-update

# PAM module to restrict access to specific users/groups
- name: enable access restrictions
  template:
    dest: /usr/share/pam-configs/access
    src: pam_config_access.j2
    owner: 'root'
    group: 'root'
    mode: 0644
  notify: pam-auth-update

- name: sssd config
  template: >
    src=sssd.conf.j2
    dest=/etc/sssd/sssd.conf
    mode=0600
    owner=root
    group=root
  notify: restart sssd

# This issue is temporary.. but in the meantime, insufferable.
# https://bugs.launchpad.net/ubuntu/+source/bash-completion/+bug/1390061
- name: Copy bash completion patch
  copy:
    src: bash_completion.patch
    dest: /tmp/bash_completion.patch
- name: Check for patch
  stat:
    path: /usr/share/bash-completion/bash_completion.patched
  register: bash_is_patched
  changed_when: false
- name: Install patch
  apt:
    name: patch
- name: Apply bash completion patch
  shell: patch /usr/share/bash-completion/bash_completion /tmp/bash_completion.patch && touch /usr/share/bash-completion/bash_completion.patched
  when: not bash_is_patched.stat.exists
