---
# handlers file for authconfig

# --enablemkhomedir only seems to work if --savebackup isn't specified so it was moved to a handler
# invoked after oddjob is started.
- name: authconfig mkhomedir
  command: "/usr/sbin/authconfig --enablemkhomedir --update"
#  args:
#    creates: /var/lib/authconfig/backup-ansible_configured2
  notify: restart sssd

- name: restart sssd
  service:
    name: sssd
    enabled: yes
    state: restarted

- name: restart oddjob
  service:
    name: oddjobd
    enabled: yes
    state: restarted

- name: restart ssh
  service:
    name: sshd
    enabled: yes
    state: restarted
  when: ansible_distribution == 'Redhat' or ansible_distribution == 'CentOS'

- name: restart ssh
  service:
    name: ssh
    enabled: yes
    state: restarted
  when: ansible_distribution == 'Ubuntu'

- name: pam-auth-update
  command: /usr/sbin/pam-auth-update --package
